name: incredux
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/shindakioku/incredux
author: shindakioku <shindakioku@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  redux: ^3.0.0

dev_dependencies:
  test: ^1.0.0
